# CMSC 197 - QUIZ 1
AREN DEZA, 2019-50022<br>BS Compsci 4, Section 1
## [ PART 1. REGRESSION LOSS FUNCTIONS ]

In [7]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


### Creating 2 arrays, y_hat and y
**y_hat** is initialized with 20 linearly spaced numbers between -1 and 1.<br>
**y** is initialized with 20 linearly spaced numbers between 0 and 1.

To accomplish this, we use the Numpy function **np.linspace()** which returns <br>
a specified number of linearly spaced numbers between a given upper and lower limit.

In [8]:
y_hat = np.linspace(-1,1,20)
y = np.linspace(0,1,20)

y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [9]:
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Computing for the shape and dimension of y_hat and y

In [10]:
print("y_hat shape:     ", y_hat.shape)
print("y_hat dimension: ", y_hat.ndim)

y_hat shape:      (20,)
y_hat dimension:  1


In [11]:
print("y shape:     ", y.shape)
print("y dimension: ", y.ndim)

y shape:      (20,)
y dimension:  1


### Creating individual functions for each of the loss functions <br> using y and y_hat as parameters
This value N will be used for each of the loss functions below. <br>
Changing it here will affect the results, so feel free to change it as needed. <br><br>
However, please note that it will never go above 20, as that will go out of bounds.

In [13]:
N = int(input("Please enter a value for N: "))
if N > 20:
    N = 20
N

Please enter a value for N: 10


10

### Part 1-1. Mean Squared Error

In [14]:
L = 0

for i in range(0,N):
    L = L + (y_hat[i] - y[i])**2

L = L * (1/N)

In [15]:
L

0.6052631578947368

### Part 1-2. Mean Absolute Error

In [16]:
L = 0

for i in range(0,N):
    L = L + abs(y_hat[i] - y[i])

L = L * (1/N)

In [17]:
L

0.7631578947368423

### Part 1-3. Mean Squared Logarithmic Error
This was executed using the given rules. Here, we <u>do not perform MSLE if we have any negative target variables.</u><br>
Otherwise, we will check if **y_hat** and **y** have any zeroes. If they both have no zeroes, we will forego having to add 1 in our logarithm steps.

In [18]:
L = 0
no_negatives = True
no_zeroes = True

for i in range(0,20):
    if (y_hat[i]<0) or (y[i]<0):    # Checking for negative target variables
        no_negatives = False
        break
    if (y_hat[i]==0) or (y[i]==0):  # Checking for zeroes
        no_zeroes = False
        continue

if no_negatives:
    if no_zeroes:                   # If target is never zero, the addition of 1 can be dropped
        for i in range(0,N):
            L = L + (log(y_hat[i]) - log(y[i]))**2
        L = L * (1/N)
    else:
        for i in range(0,N):
            L = L + (log(y_hat[i]+1) - log(y[i]+1))**2
        L = L * (1/N)
else:
    L = "Array has negative target variables. Cannot perform MSLE"

In [19]:
L

'Array has negative target variables. Cannot perform MSLE'

### Part 1-4. Mean Absolute Percentage Error
To avoid instances of zero division, we just skip over any instance where it may happen.

In [20]:
L = 0

for i in range(0,N):
    if y[i] == 0:      # No zero division
        continue
    else:
        L = L + abs((y_hat[i] - y[i])/y[i])

L = L * (100/N)

In [21]:
L

447.50396825396825

## [ PART 2. APPLICATION OF LESSONS ]

### Creating a 1d array M {1, 2, ...16} using the arange function
As discussed in class, it works in such a way that **[bottom, top)**

In [22]:
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Reshaping M into 4x4 array and store it to N
To do this, we use the **np.reshape()** function to convert our 1D array into a 4x4 one.<br>
Here, we adjust the parameters to get the desired 4 rows and 4 columns.

In [23]:
M = np.reshape(M,(1,4,4))[0]
N = M
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Getting the 2nd row of N

In [24]:
N[1]

array([5, 6, 7, 8])

### Getting the minimum values for each column of N
Numpy provides us with the **np.min** function to return the minimum value within a given matrix. <br>
Here, we can restrict its use to each individual column while iterating through a for loop to get the results we need.

In [25]:
for j in range(0,len(N)):
    print("min value in col", j, "is", np.min(N[:,j]))

min value in col 0 is 1
min value in col 1 is 2
min value in col 2 is 3
min value in col 3 is 4


### Get the locations of the minimum values for each column of N
**np.where()** can be used to find the indices of any element within an array that fits certain conditions set by the user. <br> Here, we combine this function with **np.min()** to find the indices of each minimum value.<br><br>
Afterwards, we just extract the relevant information from the results of **np.where** <br>and then we format them to fit our **array_name[row,col]** format

In [26]:
for j in range(0,len(N)):
    row = np.where(N == np.min(N[:,j]))[0][0]
    col = np.where(N == np.min(N[:,j]))[1][0]
    print("location of min value in col", j, "is", "N["+str(row)+","+str(col)+"]")

location of min value in col 0 is N[0,0]
location of min value in col 1 is N[0,1]
location of min value in col 2 is N[0,2]
location of min value in col 3 is N[0,3]


### Getting average of whole matrix
For this, we use **np.mean** which returns the average of the entire matrix

In [27]:
np.mean(N)

8.5

### Creating a vector V with 4 elements, each element is 1

In [28]:
V = np.array([1,1,1,1])
V

array([1, 1, 1, 1])

### Taking the dot product of N and V

In [29]:
np.dot(N, V)

array([10, 26, 42, 58])